Repository d3b-center/d3b-release-maker, pull requests merged in 2020-07, with the labels that each got.

#23 ✨ Set default repo from git
  d3b_release_maker/cli.py
Labels: feature

#27 🏷 Release 1.3.0
  CHANGELOG.md
Labels: release

#29 🐛 Catch newly merged PRs opened before last release
  d3b_release_maker/release_maker.py
Labels: bug

#30 🏷 Release 1.4.0
  CHANGELOG.md
Labels: release

#33 🏷 Release 1.4.1
  CHANGELOG.md
Labels: release
